import type { Product } from '@/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Lechuga Romana Fresca',
    description: 'Crujiente y deliciosa lechuga Romana, cultivada localmente.',
    longDescription: 'Nuestra lechuga Romana es cultivada con métodos sostenibles, garantizando frescura y sabor incomparables. Perfecta para ensaladas y sandwiches.',
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Verduras',
    price: '$1.50 / unidad',
    producerName: 'Granja Sol Radiante',
    dataAiHint: 'lettuce fresh',
  },
  {
    id: '2',
    name: 'Tomates Cherry Orgánicos',
    description: 'Dulces y jugosos tomates cherry, perfectos para snacks y ensaladas.',
    longDescription: 'Estos tomates cherry orgánicos están llenos de sabor y son cultivados sin pesticidas. Ideales para dar un toque de color y dulzura a tus platos.',
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Frutas',
    price: '$3.00 / canasta',
    producerName: 'Huerto El Roble',
    dataAiHint: 'cherry tomatoes',
  },
  {
    id: '3',
    name: 'Zanahorias Tiernas',
    description: 'Zanahorias frescas y tiernas, ricas en vitaminas.',
    longDescription: 'Cosechadas en su punto óptimo, nuestras zanahorias son crujientes y naturalmente dulces. Excelentes crudas, cocidas o en jugos.',
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Verduras',
    price: '$2.00 / manojo',
    producerName: 'Finca La Esperanza',
    dataAiHint: 'carrots bunch',
  },
  {
    id: '4',
    name: 'Papas Nativas',
    description: 'Variedad de papas nativas con sabores únicos.',
    longDescription: 'Descubre la diversidad de las papas nativas, cada una con una textura y sabor distintivo. Ideales para purés, asados o guisos.',
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Tubérculos',
    price: '$2.50 / kg',
    producerName: 'Comunidad Andina',
    dataAiHint: 'potatoes variety',
  },
  {
    id: '5',
    name: 'Cebolla Roja Fresca',
    description: 'Cebollas rojas de sabor intenso, perfectas para ensaladas y guisos.',
    longDescription: 'Nuestras cebollas rojas son cultivadas para ofrecer un sabor robusto y una textura crujiente. Un ingrediente esencial en cualquier cocina.',
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Verduras',
    price: '$1.80 / kg',
    producerName: 'Granja Sol Radiante',
    dataAiHint: 'red onions',
  },
  {
    id: '6',
    name: 'Albahaca Fresca Orgánica',
    description: 'Manos de albahaca aromática, ideal para pestos y platos italianos.',
    longDescription: 'Albahaca orgánica de aroma intenso, cultivada de forma natural para preservar todas sus propiedades. Perfecta para salsas, ensaladas y como toque final en tus platos.',
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Hierbas',
    price: '$2.20 / manojo',
    producerName: 'Huerto El Roble',
    dataAiHint: 'basil fresh',
  },
];
